# Generated by Django 4.2.4 on 2024-03-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('nombreRango', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcionRango', models.CharField(max_length=255)),
                ('cantidadRango', models.IntegerField()),
                ('desExpRango', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rangos',
            },
        ),
    ]
