# Generated by Django 4.2.4 on 2024-03-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rangos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rangos',
        ),
    ]
