# Generated by Django 4.2.4 on 2024-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rangos', '0002_delete_rangos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rangos',
            fields=[
                ('idRango', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreRango', models.CharField(max_length=50)),
                ('descripcionRango', models.CharField(max_length=255)),
                ('cantidadRango', models.IntegerField()),
                ('desExpRango', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rangos',
            },
        ),
    ]
