# Generated by Django 4.2.4 on 2024-03-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='miembros',
            table=None,
        ),
    ]
