# Generated by Django 4.2.4 on 2024-03-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_alter_miembros_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miembros',
        ),
    ]
