# Generated by Django 4.2.4 on 2024-03-28 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rangos', '0008_alter_rangos_activo'),
        ('pelotones', '0005_rename_ubicaciónp_pelotones_ubicacionp'),
        ('miembros', '0005_delete_miembros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembros',
            fields=[
                ('idMiembro', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreM', models.CharField(max_length=50)),
                ('apellidosM', models.CharField(max_length=50)),
                ('edadM', models.CharField(max_length=3)),
                ('direcciónM', models.CharField(max_length=50)),
                ('telefonoM', models.CharField(max_length=10)),
                ('correoM', models.EmailField(max_length=254)),
                ('fotoM', models.CharField(max_length=255)),
                ('fechaIngresoM', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('activo', models.CharField(max_length=6)),
                ('peloton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelotones.pelotones')),
                ('rango', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangos.rangos')),
            ],
        ),
    ]
