# Generated by Django 4.2.4 on 2024-03-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miembros',
        ),
    ]
