# Generated by Django 4.2.4 on 2024-03-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='fotoM',
            field=models.ImageField(null=True, upload_to='miembros/'),
        ),
        migrations.AlterField(
            model_name='miembros',
            name='telefonoM',
            field=models.CharField(max_length=15),
        ),
    ]
