# Generated by Django 4.2.4 on 2024-03-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0010_alter_miembros_fotom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembros',
            name='fotoM',
            field=models.ImageField(null=True, upload_to='miembros/'),
        ),
    ]
