# Generated by Django 4.2.4 on 2024-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelotones',
            fields=[
                ('idPeloton', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreP', models.CharField(max_length=30)),
                ('descripcionP', models.CharField(max_length=255)),
                ('ubicaciónP', models.CharField(max_length=255)),
                ('cantidadP', models.IntegerField()),
            ],
            options={
                'db_table': 'Pelotones',
            },
        ),
    ]
