# Generated by Django 4.2.4 on 2024-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelotones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelotones',
            name='cantidadP',
            field=models.IntegerField(null=True),
        ),
    ]
