# Generated by Django 4.2.4 on 2024-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelotones', '0002_alter_pelotones_cantidadp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelotones',
            name='activo',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
