# Generated by Django 4.2.4 on 2024-03-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelotones', '0003_pelotones_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelotones',
            name='activo',
            field=models.CharField(max_length=6),
        ),
    ]
