# Generated by Django 4.2.4 on 2024-03-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelotones', '0004_alter_pelotones_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelotones',
            old_name='ubicaciónP',
            new_name='ubicacionP',
        ),
    ]
