# Generated by Django 4.2.4 on 2024-04-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelotones', '0005_rename_ubicaciónp_pelotones_ubicacionp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelotones',
            name='cantidadP',
        ),
    ]
